
CREATE TABLE TBL_QUESTOES (
	ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	TITULO VARCHAR(2000) NOT NULL,
	FG_QUESTAO_ATIVA VARCHAR(2),
	TX_OPCAO_A VARCHAR(2000) NOT NULL,
	TX_OPCAO_B VARCHAR(2000) NOT NULL,
	TX_OPCAO_C VARCHAR(2000) NOT NULL,
	TX_OPCAO_D VARCHAR(2000) NOT NULL,
	TX_OPCAO_E VARCHAR(2000) NOT NULL,
	FG_VERD_A VARCHAR(2),
	FG_VERD_B VARCHAR(2),
	FG_VERD_C VARCHAR(2),
	FG_VERD_D VARCHAR(2),
	FG_VERD_E VARCHAR(2),
	PRIMARY KEY(ID)
);

